apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '"trace_id":"([^"]*)"'
          name: trace_id
          url: '$${__value.raw}'
        - datasourceUid: tempo  
          matcherRegex: 'trace_id=([a-zA-Z0-9]+)'
          name: trace_id
          url: '$${__value.raw}'
