apiVersion: 1

datasources:
  - name: tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    editable: true
    jsonData:
      httpMethod: GET
      # Disable service map to avoid metrics queries that cause empty ring errors
      serviceMap:
        datasourceUid: ''
      # Disable node graph and metrics queries
      nodeGraph:
        enabled: false
      # Limit search to traces only, not metrics
      search:
        hide: false
      # Disable span metrics that require metrics generator
      spanMetrics:
        datasourceUid: ''
      # Configure trace to logs (optional)
      tracesToLogs:
        datasourceUid: ''
        tags: ['job', 'instance', 'pod', 'namespace']
        mappedTags: []
        mapTagNamesEnabled: false
        spanStartTimeShift: ''
        spanEndTimeShift: ''
        filterByTraceID: false
        filterBySpanID: false
