global:
  scrape_interval: 15s

scrape_configs:
  # Prometheus monitors itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    # You can add relabel_configs here if needed for custom labels

  # FastAPI metrics endpoint
  - job_name: 'fastapi'
    static_configs:
      - targets: ['api:8000']
    metrics_path: /metrics
    
  # k6 metrics endpoint
  - job_name: 'k6'
    static_configs:
      - targets: ['k6:6565']
    metrics_path: /metrics
    scrape_interval: 5s
