# Grafana Alerting Configuration for Tempo
# Note: These are alerting rule templates - actual alerts would require
# Tempo metrics generator to be enabled and Prometheus to scrape span metrics

apiVersion: 1

# Contact points for alert notifications
contactPoints:
  - name: default-contact-point
    uid: default
    receivers:
      - uid: default-receiver
        type: webhook
        settings:
          url: http://localhost:3000/webhook
          httpMethod: POST

# Notification policies
policies:
  - receiver: default-contact-point
    group_by:
      - grafana_folder
      - alertname
    group_wait: 10s
    group_interval: 5m
    repeat_interval: 12h

# Alert rule groups (commented out since they require span metrics)
# groups:
#   - name: tempo_alerts
#     folder: Observability
#     interval: 1m
#     rules:
#       - uid: high-error-rate
#         title: High Error Rate
#         condition: A
#         data:
#           - refId: A
#             queryType: ""
#             relativeTimeRange:
#               from: 300
#               to: 0
#             model:
#               expr: |
#                 (
#                   sum(rate(traces_spanmetrics_calls_total{status_code="STATUS_CODE_ERROR"}[5m])) by (service_name) 
#                   / 
#                   sum(rate(traces_spanmetrics_calls_total[5m])) by (service_name)
#                 ) > 0.05
#         noDataState: NoData
#         execErrState: Alerting
#         for: 2m
#         annotations:
#           summary: "High error rate detected in service {{ $labels.service_name }}"
#           description: "Service {{ $labels.service_name }} has error rate of {{ $value | humanizePercentage }}"
